### ISSUE TITLE
[JNPCT Adolescent]: App Development - Visit Schedule - May 2024

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#16]
- [x] Create this new visit scheduling for all the forms in UAT in the JNPCT Adolescent Organization.
- [x] After the first Child Follow up, the subsequent follow up will be scheduled based on the severity of the Nutrition or Anaemic status(any one which is more serious) in each child Follow up encounter.
- [x] [Refer to this link for visit scheduling.](https://docs.google.com/spreadsheets/d/1GiCdqctT9DPSFm692epD8g4sI-DJMi-j/edit#gid=21272168&range=18:26)

> **Note**

- [x] Add a check if the program is exited or the visit cancel reason is "Death" then no visits should get scheduled
- [x] Test on completion and on Cancellation both

**Comment by Dinesh2019** [comment]
@adamsanadi6  the status of anemia is mild and nutrition status is severely underweight the follow-up visit is scheduled for severely underweight. But the expected result is the first status the corresponding follow-up is scheduled which should be mild anemia follow need to be scheduled.

**Comment by Dinesh2019** [comment]
@adamsanadi6 as discussed with him accroding to requirement sheet logic, the visit get scheduled
