### ISSUE TITLE
[JNPCT Adolescent]: App Development - Offline Dashboard

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/JNPCT-Adolescent#18]
- [x] Create this Offline Dashboard in UAT in the JNPCT Adolescent Organization
 - [x] [Offline Dashboard Requirement](https://docs.google.com/spreadsheets/d/1GiCdqctT9DPSFm692epD8g4sI-DJMi-j/edit#gid=360729605)

**Comment by Dinesh2019** [comment]
@adamsanadi6 @AnjaliBhagabati, do we need to implement the age logic for the custom card of Nutritional Status and Anaemia Status? Currently, we are displaying the individual on the card even if their age is greater than 19.

**Comment by AnjaliBhagabati** [comment]
@adamsanadi6 yes we should implement the age logic in the custom cards for Anaemia and Nutritional status cards. It should not show individual with age more than 19 years

**Comment by adamsanadi6** [comment]
@Dinesh2019 @AnjaliBhagabati I have added the check. Dinesh you can test it out.
