### ISSUE TITLE
[JNPCT Adolescent]: Locations and User & Catchment upload in production and User Group Permissions.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#25]
- [x] Location and Users Upload in the new Format

1. Download the Users and Catchment Sample from the Upload section of the Admin console, as the format has changed. 
You need to create the users and catchment list in the new format and upload

2. Download the locations sample from the Upload section of the Admin console. Add the locations in the given format and upload it.

[Checklist](https://docs.google.com/document/d/1PPmJpLEyxyh2I2CW4kxmz_EDQcmGp6NjLqRFWM6Hbsk/edit)

[User & Catchment](https://docs.google.com/spreadsheets/d/1bdEQaMztZq5Zzur-MFqAmzoT54GOlq6JklXggdb7apg/edit?gid=364227816#gid=364227816)

[User Groups and Permissions](https://docs.google.com/spreadsheets/d/1iMiZR-NLhS5H3RSMWVjqvNt6YGilJSPPfok6_d6O0hE/edit?gid=2070729981#gid=2070729981)

**Comment by Dinesh2019** [comment]
created the new catchment for the below users

Dr. Dhiren Modi
Mahendra J. Pawar
Surekha R. Lakhan
Arjunsinh J. Jadav
Vinod R. Vaijal
