### ISSUE TITLE
[JNPCT Adolescent]: UAT Testing Card - Do not schedule backdated visits. Visit should be scheduled only for current or future dates.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#27]

**Comment by Dinesh2019** [comment]
@kameshbhariya what is the use case for this card to test it. Scheduling date depends on the logic written in the app designer

**Comment by Dinesh2019** [comment]
@tested in UAT, we are not scheduling any backdate visits.
