### ISSUE TITLE
[JNPCT Adolescent]: Testing Card - Do not schedule backdated visits. Visit should be scheduled only for current or future dates.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#30]
The JNPCT Adolescent team will upload old data through the DEA. We need to test the below things using the sample data shared

1. They should be able to fill all the forms through the DEA (Individual Registration Form , Enrolment Form and Child Follow Up Form)
2. Once the datas are entered through the DEA and saved for the Child Follow Up Form, visit should only be scheduled for current or future dates from the current month
- [ ] Check there are no back dates visits getting scheduled

- [ ] [Sample Data](https://docs.google.com/spreadsheets/d/1Wuyf7yJwCYNufQaz3EGlI8_kpr6mSl-o/edit?gid=137588128#gid=137588128)

**Comment by pkundu** [comment]
@kameshbhariya please get some sample data - whatever they are going to upload using DEA

**Comment by Dinesh2019** [comment]
created the bug card found one issue in the csv upload https://github.com/avniproject/avni-webapp/issues/1277
