### ISSUE TITLE
[JNPCT Adolescent]: Reports: Total Adolescence

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#32]
- [x] To be created in Superset in the Production Environment
- [x] [Requirement Document](https://docs.google.com/spreadsheets/d/1e8lcXyoCZMeewKB4YQXMSMlKwstqIEM9/edit?gid=420519325#gid=420519325)

**Comment by manish-sd** [comment]
DashBoard Link: [[JNPCT Adolescent]: Reports: Total Adolescence](https://reporting-superset.avniproject.org/superset/dashboard/141/?native_filters_key=n8lJdZ7z7HRpZhGnMXkuPiPr3CnaPQIn15Dn51MouOOq6j33gb760jvGqM83eeJQ)

**Comment by adamsanadi6** [comment]
@manish-sd Please make the following changes:

- [x] Remove 'Adolescent Stage' Column from the linelist.
- [x] 'Adolescent Stage' filter can be applied on both linelist and the aggregate repot.
- [x] Date filter should be applied to the enrollment date.

**Comment by Dinesh2019** [comment]
- [x] Can we have the line list for the aggregate hostel and also filter for it.
