### ISSUE TITLE
[JNPCT Adolescent]: Stages of Adolescence out of total registration

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#33]
- [x] To be created in Superset in the Production Environment
- [x] [Requirement Document](https://docs.google.com/spreadsheets/d/1e8lcXyoCZMeewKB4YQXMSMlKwstqIEM9/edit?gid=1113582776#gid=1113582776)

**Comment by adamsanadi6** [comment]
Dashboard link: [[ JNPCT Adolescent ] Adolescent Stage](https://reporting-superset.avniproject.org/superset/dashboard/133)

**Comment by adamsanadi6** [comment]
@sachsk / @nupoorkhandelwal Please review the report.

**Comment by nupoorkhandelwal** [comment]
@adamsanadi6 
You can remove Adolescent Stage column from the report

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal Changes have been made.
