### ISSUE TITLE
[JNPCT Adolescent]: Status of Malnutrition among Adolescence

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#34]
- [x] To be created in Superset in the Production Environment
- [x] [Requirement Document](https://docs.google.com/spreadsheets/d/1e8lcXyoCZMeewKB4YQXMSMlKwstqIEM9/edit?gid=1632406301#gid=1632406301)

**Comment by adamsanadi6** [comment]
Dashboard link: [[ JNPCT Adolescent ] Status of Malnutrition among Adolescence](https://reporting-superset.avniproject.org/superset/dashboard/136)

**Comment by adamsanadi6** [comment]
@sachsk / @nupoorkhandelwal Please review the report.

**Comment by nupoorkhandelwal** [comment]
@adamsanadi6 Similarly, in this report as well, you can fetch the latest encounter separately in a CTE and the join in the final query

**Comment by nupoorkhandelwal** [comment]
@adamsanadi6 Similarly, in this report as well, you can fetch the latest encounter separately in a CTE and the join in the final query

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal Changes have been made.
