### ISSUE TITLE
[JNPCT Adolescent]: Status of Anemia among Adolescence

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#35]
- [x] To be created in Superset in the Production Environment
- [x] [Requirement Document](https://docs.google.com/spreadsheets/d/1e8lcXyoCZMeewKB4YQXMSMlKwstqIEM9/edit?gid=1113582776#gid=1113582776)

**Comment by manish-sd** [comment]
Dashboard Link: [[JNPCT Adolescent]: Status of Anemia among Adolescence#35](https://reporting-superset.avniproject.org/superset/dashboard/135/?native_filters_key=UjrKj0-JOZZSSefQsnFdI-qPXgJnfkFOL0NudQ6DDaDkbvddZV4qtEnblqrI4Bvc)

**Comment by adamsanadi6** [comment]
@manish-sd Please make the following changes:

- [x] 1. Take the follow-up data from the latest encounter.
- [x] 2. Fetch the latest encounter separately in a CTE and join it in the final query.
- [x] 3. Remove Adolescent Stage column from the Linelist.
- [x] 4. Change the filter name ‘Age Range’ to ‘Age (In Years)’.
- [x] 5. Bring the 'Anemia Status' filter at the bottom and have diveder called Linelist Only Filter
- [x] 6. Marital status and Exit Reason filter can be applied to both linelist and the aggregate.

**Comment by manish-sd** [comment]
Resolved comments

**Comment by Dinesh2019** [comment]
- [x] In the line list can we move the address before the exit columns 
- [x] We also make the search box show the entire aggregate number.

References image : 

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME5kQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6dda9ed6cb4adfb89b6e4e1103a2fff2a47679ba/Screenshot%202024-08-15%20at%201.37.49%E2%80%AFPM.png" alt="Screenshot 2024-08-15 at 1.37.49 PM.png" />
