### ISSUE TITLE
[JNPCT Adolescent]: Status of Menstruation

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#37]
- [x] To be created in Superset in the Production Environment
- [x] [Requirement Document](https://docs.google.com/spreadsheets/d/1e8lcXyoCZMeewKB4YQXMSMlKwstqIEM9/edit?gid=345581658#gid=345581658)

**Comment by manish-sd** [comment]
DashBoard Link: [[JNPCT Adolescent]: Status of Menstruation](https://reporting-superset.avniproject.org/superset/dashboard/139/?native_filters_key=lHh8Iw6-GnhhreE_mEqFwS2AcQdXVUlVl7yh0WRdWU4UcLZZhPflDfiM9_KE6Qn4)

**Comment by adamsanadi6** [comment]
@manish-sd Please make the following changes:

- [x] 1. Take the follow-up data from the latest encounter.
- [x] 2. Include a gender = ‘Female’ check inside the query (not in the metric).
- [x] 3. Fetch the latest encounter separately in a CTE and join it in the final query.
- [x] 4. Include the Age column in the Linelist.
- [x] 5. Remove Adolescent Stage column from the Linelist.
- [x] 6. Change the filter name ‘Age Range’ to ‘Age (In Years)’.
- [x] 7. The Linelist is showing male records as well; the gender check is missing.
- [x] 8. Remove Gender column from the Linelist, as we are showing only female data.
- [x] 9. In the Address Filter, PHC should depend on Block, and Subcentre should depend on both Block & PHC. Similarly, Village and Faliya should depend on their respective parent levels.
- [x] 10. Remove Gender Filter.
- [x] 11. Bring the 'Menstruation Started' filter at the bottom and have diveder called Linelist Only Filter 
- [x] 12. Marital status and Exit Reason filter can be applied to both linelist and the aggregate.


<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnBSQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd4531cc50dd7d301e45de14c172c28475f98b30/Screenshot%202024-08-13%20at%202.31.21%E2%80%AFPM.png" alt="Screenshot 2024-08-13 at 2.31.21 PM.png" />

**Comment by manish-sd** [comment]
Resolved comments
