### ISSUE TITLE
[JNPCT Adolescent]: Menstrual Absorbent

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#38]
- [x] To be created in Superset in the Production Environment
- [x] [Requirement Document](https://docs.google.com/spreadsheets/d/1e8lcXyoCZMeewKB4YQXMSMlKwstqIEM9/edit?gid=794511223#gid=794511223)

**Comment by adamsanadi6** [comment]
Dashboard link: [[JNPCT Adolescent] Menstrual Absorbent](https://reporting-superset.avniproject.org/superset/dashboard/137)

**Comment by adamsanadi6** [comment]
@sachsk / @nupoorkhandelwal Please review the report.

**Comment by nupoorkhandelwal** [comment]
@adamsanadi6 
1. You can remove Gender column from the report
2. You can remove Adolescent Stage column from the report
3. Similarly, in this report as well, you can fetch the latest encounter separately in a CTE and the join in the final query

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal Changes have been made.

**Comment by Dinesh2019** [comment]
missed to add the column in aggregate Girls with complaint during menses

**Comment by adamsanadi6** [comment]
Added the "Age at Menarche" column in the linelist.
