### ISSUE TITLE
[JNPCT Adolescent]: Girls with menstrual problem

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#39]
- [x] To be created in Superset in the Production Environment
- [x] [Requirement Document](https://docs.google.com/spreadsheets/d/1e8lcXyoCZMeewKB4YQXMSMlKwstqIEM9/edit?gid=12999127#gid=12999127)

**Comment by manish-sd** [comment]
DashBoard Link: [[JNPCT Adolescent]: Girls with menstrual problem](https://reporting-superset.avniproject.org/superset/dashboard/138/?native_filters_key=C_Hsyj61J18dcRSUID7prb89EZMRYgDGi026vGMEJA_zPDEhUCcABzp9GZfdTEF4)

**Comment by adamsanadi6** [comment]
@manish-sd Please make the following changes:

- [x] 1. Take the follow-up data from the latest encounter.
- [x] 2. Include a gender = ‘Female’ check inside the query (not in the metric).
- [x] 3. Fetch the latest encounter separately in a CTE and join it in the final query.
- [x] 4. Remove Adolescent Stage column from the Linelist.
- [x] 5. Change the filter name ‘Age Range’ to ‘Age (In Years)’.
- [x] 6. The Linelist is showing male records as well; the gender check is missing.
- [x] 7. Remove Gender column from the Linelist, as we are showing only female data.
- [x] 8. In the Address Filter, PHC should depend on Block, and Subcentre should depend on both Block & PHC. Similarly, Village and Faliya should depend on their respective parent levels.
- [x] 9. Remove Gender Filter.
- [x] 10. Marital status, Exit Reason and Absorbent Used filter can be applied to both linelist and the aggregate.

**Comment by manish-sd** [comment]
Resolved comments
