### ISSUE TITLE
[JNPCT Adolescent]: Operational Dashboard - Sync Telemetry

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#41]
- [x]  To be created in Superset in the Production Environment
- [x]  [Requirement Document](https://docs.google.com/spreadsheets/d/1e8lcXyoCZMeewKB4YQXMSMlKwstqIEM9/edit?gid=412189579#gid=412189579)

Note: add org_id check whenever you join sync_telemetry

---
**Dashboard Link :**[Link](https://reporting-superset.avniproject.org/superset/dashboard/132/?native_filters_key=civiF2WqpXnQm8vKaZgQVYBIrcqQMwBpzAT-_-1iKG8GnjFipduq18QEStCjKi0s)

**Comment by Dinesh2019** [comment]
@vedfordev can we add the filter for sync status so that cilent see the complete and incomplete data separately

**Comment by vedfordev** [comment]
@Dinesh2019 not require. as we earlier never give.
