### ISSUE TITLE
[JNPCT Adolescent]: Operational Dashboard - Completed Visit

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#42]
- [x]  To be created in Superset in the Production Environment
- [x]  [Requirement Document](https://docs.google.com/spreadsheets/d/1e8lcXyoCZMeewKB4YQXMSMlKwstqIEM9/edit?gid=412189579#gid=412189579)

**Comment by adamsanadi6** [comment]
Dashboard link : [Operational Dashboard](https://reporting-superset.avniproject.org/superset/dashboard/132)

**Note:** For all 4 completed, cancelled, scheduled and overdue visits, I'm using the same data set called All Visits.
