### ISSUE TITLE
[JNPCT Adolescent]: Visit Scheduling Issue

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/JNPCT-Adolescent#48]
- [x] Changes to be done in UAT first
- [x] The client is going to enter old data using the DEA. To ensure that back dated visits do not get scheduled because of the old data upload, we have added a rule in the [visit scheduling](https://docs.google.com/spreadsheets/d/1GiCdqctT9DPSFm692epD8g4sI-DJMi-j/edit?gid=21272168#gid=21272168) (Do not schedule back dated visits. Visit should only be scheduled for current or future dates from the current month) but still back dated visits are getting scheduled
- [x] While testing [this card](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/jnpct-adolescent/30) we found that back dated visits are getting scheduled (It is getting scheduled basis the encounter date) because of which visits are getting scheduled for year 2022, 2021 etc

**Note**
Add the date 1st july 2024 encounters which are scheduled before this date should not schedule any visit
Add this rule on individual, enrolment and encounter wherever visit scheduling logic present.
compare date with encounter date

**Comment by vedfordev** [comment]
@AnjaliBhagabati @Dinesh2019 As discussed I changed in program only. it will check if date is before today then earliest visit date will be today.

**Comment by vedfordev** [comment]
@Dinesh2019 @sachsk As discuss over call, I added condition that if earliestDate is before 1st july 2024 then it will not schedule visit.
cc : @AnjaliBhagabati

**Comment by Dinesh2019** [comment]
@AnjaliBhagabati @sachsk @vedfordev If the individual is registered on 1 Jun 2024 and enrolled on 1 Jun 2024 then we will not schedule any visit for that individual if the registration happens after the 1 July 2024 then only we are going to follow the process follow. As discussed client has to give the date according to the date the system will behave.
