### ISSUE TITLE
[JNPCT Adolescent]: App Development - Adolescent Child Follow Up Form - May 2024

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#5]
- [x] Create this new form in UAT in the JNPCT Adolescent Organization.
- [x] [Adolescent Child Follow Up Form](https://docs.google.com/spreadsheets/d/1GiCdqctT9DPSFm692epD8g4sI-DJMi-j/edit#gid=1749129201)
- [x] Details Regarding  Menstrual Hygiene section will only will show if Gender is Female in Registration

**TECH TASKS **

- [x] Add a check in visit scheduling - If the age of individual is more than 19 years on or after earliest visit date of the next visit then do not schedule further visits
- [x] Add the same check in cancellation of visit
- [x] Add a validation, if age of the ind is > 19 years as per encounter date then show an error message - " Cancel the visit and exit the individual form the Adolescent program as age of individual is more than 19 years"

**Comment by Dinesh2019** [comment]
@adamsanadi6 @AnjaliBhagabati as discussed moving this card back to On hold we need to confirm what happening if chid age is greater than 19 while completing the encounter

**Comment by AnjaliBhagabati** [comment]
@nupoorkhandelwal @adamsanadi6 as discussed on the call, 

- [x] if an individual age is >19 years we need to add a validation rule in the visit schedule which checks the age of an individual, and if it is >19 year, we should not allow user to fill this form.

- [x] Show an error message stating "Individual's age is greater than the program eligibility age (19 years), kindly cancel this form and exit the program"

**Comment by AnjaliBhagabati** [comment]
@nupoorkhandelwal @adamsanadi6 as discussed on the call, 

- [x] if an individual age is >19 years we need to add a validation rule in the visit schedule which checks the age of an individual, and if it is >19 year, we should not allow user to fill this form.

- [x] Show an error message stating "Individual's age is greater than the program eligibility age (19 years), kindly cancel this form and exit the program"
