### ISSUE TITLE
Changes in unplanned  encounter for the backdated data entry

### ISSUE THREAD

**Issue by sachsk** [avniproject/JNPCT-Adolescent#54]
Do this on UAT 
### Issue:
Client needs to input back data into the system, and we are not scheduling visits for entries prior to August 31, 2024. Therefore, we need to grant access for unplanned visits.

### Tech task

**Add rule in encounter eligibility**

Hide **_Child Follow Up_** unplanned visit for below scenarios 
- [x]  if individual has the scheduled(planned) visit with earliest date after 31 August 2024
- [x]  If has completed encounter with encounter_date after 31 August 2024
- [x]  If has enrolment date after 31 August 2024

**Bug Card :** [Card](https://github.com/avniproject/avni-client/issues/1464)

**Comment by Dinesh2019** [comment]
[Test case](https://docs.google.com/spreadsheets/d/1GiCdqctT9DPSFm692epD8g4sI-DJMi-j/edit?gid=2060907436#gid=2060907436)

**Comment by Dinesh2019** [comment]
created the bug card : https://github.com/avniproject/avni-webapp/issues/1286

**Comment by vedfordev** [comment]
@Dinesh2019 for future date ageInYears will not work properly because in rule server it takes server date time. So if it will work for same date then it will work in future.

**Comment by Dinesh2019** [comment]
We have known issue check or above comment and also for 31 August 2024 the visit gets scheduled.

References video for planning : 

1.[video link](https://drive.google.com/file/d/1027cMJOccc_MTgN1SZf9FmADkwlippck/view?usp=drive_link)

2.[Video link](https://drive.google.com/file/d/1p73kKqZhXzJFn_PEzn_gq3uFrVbEiWee/view?usp=drive_link)
