### ISSUE TITLE
[JNPCT Adolescent]: Move all operational dashboard to production.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#55]
Move all operational dashboards to production.

- [x] Scheduled Visit
- [x] Completed Visit
- [x] Overdue Visit
- [x] Cancelled Visit
- [x] Individual Registration
- [x] Sync Telemetry

**Comment by Dinesh2019** [comment]
Sync Telemetry line list is empty and also active count is zero but as per the below query it show 20 individuals

tested the values with the below query

select distinct u.username from adjnpct.users u 
join adjnpct.sync_telemetry st on u.id = st.user_id 
where u.is_voided = false ;

**Comment by adamsanadi6** [comment]
Dahboard link: [Operation Dashboard](https://reporting-superset.avniproject.org/superset/dashboard/132)
