### ISSUE TITLE
[JNPCT Adolescent]: "Number of family members" and "Mother's Education" question in Individual Registration should be non-mandatory.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#56]
- [x] "[Number of family members](https://docs.google.com/spreadsheets/d/1GiCdqctT9DPSFm692epD8g4sI-DJMi-j/edit?gid=719561552#gid=719561552&range=11:11)" and "[Mother's Education](https://docs.google.com/spreadsheets/d/1GiCdqctT9DPSFm692epD8g4sI-DJMi-j/edit?gid=719561552#gid=719561552&range=27:27)" questions in individual registration should be **non-mandatory** in UAT.

**Comment by Dinesh2019** [comment]
Refer video : 


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0lQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e8885d977db1c92ea6af8ca26d19d8a85d6c105/Screen%20Recording%202024-07-26%20at%207.00.17%E2%80%AFAM.mov
