### ISSUE TITLE
[JNPCT Adolescent]: Changes in child followup form.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#57]
Make the changes in UAT.

- [x] "[Any kind of illness occurred since the last visit?](https://docs.google.com/spreadsheets/d/1GiCdqctT9DPSFm692epD8g4sI-DJMi-j/edit?gid=1749129201#gid=1749129201&range=34:35)" in the Child Followup Form, should be asked from the second follow-up onwards.
If Yes is selected, then open the textbox to enter the illness. Make this change in UAT.

- [x] "[Do girls get refreshment in Angandwadi?](https://docs.google.com/spreadsheets/d/1GiCdqctT9DPSFm692epD8g4sI-DJMi-j/edit?gid=1749129201#gid=1749129201&range=29:30)" in the Child Followup form, with options as Yes and No.
If yes is answered, then ask a follow-up question, "Do you eat the refreshment?" with options Yes and No. Make this change in UAT.

 
- [x] "[Has the child received the tetanus vaccine?](https://docs.google.com/spreadsheets/d/1GiCdqctT9DPSFm692epD8g4sI-DJMi-j/edit?gid=1749129201#gid=1749129201&range=10:10)" in the Child Followup form, with options as Yes and No.
Logic: If answered in any of the child follow-up forms as yes, then don't show this question in subsequent follow-ups. Make this change in UAT.

**Comment by Dinesh2019** [comment]
Note : 

As discussed with vedant on editing the form this logic will not be applied 


QA Video references : 

[Click here for video link](https://drive.google.com/file/d/1Ja9W7PO0P7V80Uf6C1iAb8BEH95cqgHX/view?usp=drive_link)
