### ISSUE TITLE
[JNPCT Adolescent]: Rename the Child to Adolescent from the entire app.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#58]
- [x] Rename the Child to Adolescent from the entire app. Make this change in UAT.
- [x] Changes to be made in the forms.
- [x] Changes to be made in offline dashboards.
- [x] Changes to be made in operational dashboards.

### Tech tasks

- [x] Make sure the visit scheduling rule does not break
- [x] Test all the rules, check for rule failure telemetry

- [x] Recreate ETL Table by dropping schema
- [x] Change all queries which uses the enrolment table in the operational dashboard on superset 

**Update the offline reports**

- [x] Total count of Normal
- [x] Total count of Mildly Anaemic
- [x] Adolescents To be Exited
- [x] Total count of  Normal Weight
- [x] Total count of Moderately Anaemic
- [x] Total count of Moderately Underweight
- [x] Total count of Severe Anaemic
- [x] Total count of Severly Underweight
- [x] Total count of Mildly Underweight

**Comment by Dinesh2019** [comment]
- [x] The visit is not getting scheduled after enrollment and also after completing the encounter.

Refer video : 

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3NVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--74c8840cee5fd0d0adcd9ae83e6bdf8030dddbf0/Screen%20Recording%202024-07-27%20at%208.54.51%E2%80%AFAM.mov
