### ISSUE TITLE
[JNPCT Adolescent]: Edit Access for child followup form for supervisor and cluster incharge.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#59]
- [x] Edit Access for child followup form for supervisor and cluster incharge. Make this change in UAT.

**Comment by Dinesh2019** [comment]
Refer video : 


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2tQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--981a70c2629d7b0b4eaae905092f50c0c86ab92b/Screen%20Recording%202024-07-26%20at%207.08.23%E2%80%AFAM.mov
