### ISSUE TITLE
[JNPCT Adolescent]: Change logic for a few questions in Adolescent Followup Form.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#64]
- [x] Make the changes in UAT.
- [x] Change logic for the highlighted questions in Adolescent Followup Form.
[Logic](https://docs.google.com/spreadsheets/d/1GiCdqctT9DPSFm692epD8g4sI-DJMi-j/edit?gid=1749129201#gid=1749129201&range=45:49)

------

Changes to be made in these questions logic

- [x] If using home cloth, is she counselled about hazards of using it?
- [x] How many clothes do you change in day during menses?
- [x] How do you clean the menstrual cloth?
- [x] Where do you dry the menstrual clothes after washing?
- [x] Where do you put these clothes up to the next menses?

**Comment by Dinesh2019** [comment]
QA Reference : 

[Click here to watch video](https://drive.google.com/file/d/161OWuFtFj0xPoqAVZZ6dWI2BWUw5WPxP/view?usp=drive_link)
