### ISSUE TITLE
[JNPCT Adolescent]: User creation and access for Superset, ADJNPCT reports.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#67]
- [x] Create users for ADJNPCT reports in superset and provide them with required access.
- [x] [Requirement Document](https://docs.google.com/spreadsheets/d/1FKKxeAhmPNiOZXbyAjbeEfEuTeUYjRBaDUqksLtmxUc/edit?gid=0#gid=0)

### Tech notes -

- [x] Before creating users, need to create a new gamma role for AD JNPCT. 
- [x] Assign the same to the new mentioned users.

**Comment by adamsanadi6** [comment]
Dashboard list:
1. [JNPCT Adolescent] Operational Dashboard
2. [JNPCT Adolescent] Status of Malnutrition among Adolescence
3. [JNPCT Adolescent] Anemia Status among Adolescence
4. [JNPCT Adolescent] Adolescent Stage
5. [JNPCT Adolescent]: Status of Menstruation
6. [JNPCT Adolescent] Menstrual Absorbent
7. [JNPCT Adolescent] Referral Status for Severe Anaemia
8. [JNPCT Adolescent] Girls with menstrual problem
9. [JNPCT Adolescent] Total Adolescent
