### ISSUE TITLE
[JNPCT Adolescent]: Add a condition in Adolescent Followup form.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#68]
- [x] Add a rule to display the value of Age at Menarche if it is defined/provided in any previous encounters
- [x] If the value is not defined in any of the previous encounter, let it be available for user input

- [x] [Link](https://docs.google.com/spreadsheets/d/1GiCdqctT9DPSFm692epD8g4sI-DJMi-j/edit?gid=1749129201#gid=1749129201&range=40:41)
- [x]  Make this changes in UAT and get this QA clear
- [x]  Once it is in deploy ready upload the bundle to prod.

**Comment by Dinesh2019** [comment]
@kameshbhariya do we want to hide the question and you want it only readable (because for now system shows the question and the age of merche is editable )

**Comment by kameshbhariya** [comment]
@Dinesh2019 Once these question is answered, these question should be read only and non-editable.

**Comment by kameshbhariya** [comment]
@Dinesh2019 Once these question is answered, these question should be read only and non-editable.

**Comment by Dinesh2019** [comment]
@nupoorkhandelwal if we have the value for both the questions then we can hide those questions in subsequences follow-up.

No, they want i to be dispalyed in each encounter and the reports logic is fetching these values from the latest followup. So its better that we show them as autopopulated.

**Comment by Dinesh2019** [comment]
@nupoorkhandelwal can we make this Age at Menarche question read-only.

@Dinesh2019 no, we cannot make same field read only at some point and available for user input at same time.
