### ISSUE TITLE
Optimise the offline dashboard 

### ISSUE THREAD

**Issue by sachsk** [avniproject/JNPCT-Adolescent#70]
Optimise the offline dashboard 
DO this on UAT
refer this doc : https://avni.readme.io/docs/offline-reports
Note: use minimus js try to do in Realm query only

- [ ] Total count of Normal
- [ ] Total count of Mildly Anaemic
- [ ] Adolescents To be Exited
- [ ] Total count of  Normal Weight
- [ ] Total count of Moderately Anaemic
- [ ] Total count of Moderately Underweight
- [ ] Total count of Severe Anaemic
- [ ] Total count of Severly Underweight
- [ ] Total count of Mildly Underweight

**Comment by vedfordev** [comment]
### Code Review Comment :

@nupoorkhandelwal check below :

### Code review comments 

1. In all report card for observation you have taken obeservation at last but you can use it in **filtered** check apfodisha.

2. **Adolescents To be Exited** If possible use model function for age which used in other cards.
